server.port=8083

jwt.secret=B0EA2962E150C854E4CAE41DDA28DE70
jwt.expiration=86400000

# Kafka Producer config
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
