server.port=8082

feign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.instances.userService.register-health-indicator=true
resilience4j.circuitbreaker.instances.userService.sliding-window-size=5
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.record-exceptions[0]=feign.FeignException
resilience4j.circuitbreaker.instances.userService.record-exceptions[1]=java.lang.Exception
